import {createHash,randomBytes} from "node:crypto";
import postgres from "postgres";
const sql=postgres(process.env.DATABASE_URL,{max:5,idle_timeout:20});
const SITE="https://byetale-community.vercel.app", MAX=24576;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CODE=/^[A-Za-z0-9_.:-]{1,64}$/;
const META=new Set(["renderer","locale","build_channel","network_mode","uptime_seconds","fps"]);
const hash=v=>createHash("sha256").update(v).digest("hex");
const cors=o=>({"Access-Control-Allow-Origin":o===SITE?o:SITE,"Access-Control-Allow-Headers":"content-type,x-report-token","Access-Control-Allow-Methods":"GET,POST,OPTIONS",Vary:"Origin"});
const reply=(body,status,o="")=>new Response(JSON.stringify(body),{status,headers:{...cors(o),"content-type":"application/json","cache-control":"no-store"}});
function field(v,n,required=false){if(v==null&&!required)return null;if(typeof v!=="string")throw Error("field");v=v.trim();if((required&&!v)||v.length>n)throw Error("field");return v||null}
function redact(v){if(v==null)return null;return v.replace(/[A-Z]:\\(?:[^\s\\]+\\)+[^\s]*/gi,"[ruta local omitida]").replace(/\/(?:home|Users)\/[^\s]+/g,"[ruta local omitida]").replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,"[correo omitido]").replace(/\b(?:sk|pk)_(?:live|test)_[A-Za-z0-9]+\b/g,"[secreto omitido]")}
function metadata(v){const out={};if(!v||typeof v!=="object"||Array.isArray(v))return out;for(const[k,x]of Object.entries(v)){if(!META.has(k))continue;if(typeof x==="number"&&Number.isFinite(x)||typeof x==="boolean")out[k]=x;else if(typeof x==="string")out[k]=redact(x.slice(0,120))}return out}
async function create(req,o){if(!(req.headers.get("content-type")||"").toLowerCase().startsWith("application/json"))return reply({error:"content_type_required"},415,o);if(Number(req.headers.get("content-length")||0)>MAX)return reply({error:"payload_too_large"},413,o);try{const raw=await req.text();if(!raw||new TextEncoder().encode(raw).byteLength>MAX)return reply({error:"payload_too_large"},413,o);const b=JSON.parse(raw);if(b.schema_version!==1||!UUID.test(b.installation_id||""))return reply({error:"invalid_request"},400,o);const code=field(b.error_code,64,true);if(!CODE.test(code))return reply({error:"invalid_error_code"},400,o);const install=hash(b.installation_id.toLowerCase()),token=randomBytes(32).toString("base64url"),m=metadata(b.metadata);const rows=await sql`
INSERT INTO public.game_bug_intake(access_token_hash,installation_hash,error_code,error_message,game_version,platform,scene,stack_trace,metadata)
SELECT ${hash(token)},${install},${code},${redact(field(b.message,1000,true))},${field(b.game_version,40,true)},${redact(field(b.platform,80))},${redact(field(b.scene,160))},${redact(field(b.stack_trace,6000))},jsonb_strip_nulls(jsonb_build_object('renderer',${m.renderer??null}::text,'locale',${m.locale??null}::text,'build_channel',${m.build_channel??null}::text,'network_mode',${m.network_mode??null}::text,'uptime_seconds',${m.uptime_seconds==null?null:String(m.uptime_seconds)}::text,'fps',${m.fps==null?null:String(m.fps)}::text))
WHERE (SELECT count(*) FROM public.game_bug_intake WHERE installation_hash=${install} AND created_at>now()-interval '10 minutes')<5 RETURNING id,expires_at`;
if(!rows.length)return reply({error:"rate_limited",retry_after_seconds:600},429,o);return reply({report_id:rows[0].id,report_token:token,report_url:`${SITE}/forum/reportar?report=${rows[0].id}#token=${token}`,expires_at:rows[0].expires_at},201,o)}catch(e){if(e instanceof SyntaxError)return reply({error:"invalid_json"},400,o);if(e?.message==="field")return reply({error:"invalid_request"},400,o);console.error(e);return reply({error:"internal_error"},500,o)}}
async function read(req,o,url){if(o&&o!==SITE)return reply({error:"origin_not_allowed"},403,o);const id=url.searchParams.get("report")||"",token=req.headers.get("x-report-token")||"";if(!UUID.test(id)||token.length<32||token.length>100)return reply({error:"not_found"},404,o);try{const rows=await sql`SELECT id,error_code,error_message,game_version,platform,scene,stack_trace,metadata,created_at,expires_at,claimed_at,claimed_thread_id FROM public.game_bug_intake WHERE id=${id} AND access_token_hash=${hash(token)} AND expires_at>now()`;return rows.length?reply(rows[0],200,o):reply({error:"not_found_or_expired"},404,o)}catch(e){console.error(e);return reply({error:"internal_error"},500,o)}}
export default{async fetch(req){const o=req.headers.get("origin")||"",url=new URL(req.url);if(req.method==="OPTIONS")return o===SITE?new Response(null,{status:204,headers:cors(o)}):reply({error:"origin_not_allowed"},403,o);if(req.method==="POST")return create(req,o);if(req.method==="GET")return read(req,o,url);return reply({error:"method_not_allowed"},405,o)}};
