from __future__ import annotations

import datetime as dt
import hashlib
import html
import json
import os
import pathlib
import re
import urllib.request

EXPORT_URL = os.environ.get(
    "BUG_EXPORT_URL",
    "https://br-lively-unit-aygkh67q-buglogexport.compute.c-5.us-east-2.aws.neon.tech/",
)
BASE = pathlib.Path("community/docs/bug-reports")

UUID_RE = re.compile(r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b", re.I)
HEX_RE = re.compile(r"\b0x[0-9a-f]+\b", re.I)
NUM_RE = re.compile(r"\b\d+\b")


def text(value: object) -> str:
    return "" if value is None else str(value)


def esc(value: object) -> str:
    return html.escape(text(value), quote=False)


def normalize(value: object) -> str:
    result = text(value).lower().strip()
    result = UUID_RE.sub("<uuid>", result)
    result = HEX_RE.sub("<hex>", result)
    result = NUM_RE.sub("<n>", result)
    result = re.sub(r"\s+", " ", result)
    return result[:500]


def fingerprint(report: dict[str, object]) -> str:
    trace = text(report.get("stack_trace"))
    first_trace = next((line.strip() for line in trace.splitlines() if line.strip()), "")
    parts = [
        normalize(report.get("error_code")),
        normalize(report.get("scene")),
        normalize(first_trace),
    ]
    if text(report.get("error_code")) == "PLAYER_MANUAL_REPORT":
        parts.append(normalize(report.get("message")))
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()[:16]


def code_block(value: object) -> str:
    lines = text(value).splitlines() or [""]
    return "\n".join("    " + line for line in lines)


def fetch_reports() -> list[dict[str, object]]:
    request = urllib.request.Request(
        EXPORT_URL + "?limit=500",
        headers={"User-Agent": "ByeTale-GitHub-Bug-Sync/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    if not payload.get("ok"):
        raise RuntimeError(f"bug export failed: {payload}")
    reports = payload.get("reports") or []
    if not isinstance(reports, list):
        raise RuntimeError("bug export returned an invalid reports array")
    return [item for item in reports if isinstance(item, dict)]


def render_report(report: dict[str, object]) -> str:
    report_id = text(report.get("report_id")).strip()
    fp = text(report["fingerprint"])
    metadata = report.get("metadata") if isinstance(report.get("metadata"), dict) else {}
    thread_id = text(report.get("thread_id")) or "sin-correlacion"
    forum_url = text(report.get("forum_url"))
    thread_slug = text(report.get("thread_slug"))
    forum_line = (
        f"[{esc(thread_slug or thread_id)}]({forum_url})"
        if forum_url
        else "_sin URL correlacionada_"
    )
    stack = text(report.get("stack_trace")).strip() or (
        "(sin stack trace/contexto técnico adicional en esta captura)"
    )
    metadata_rows = "\n".join(
        f"| `{esc(key)}` | `{esc(value)}` |"
        for key, value in sorted(metadata.items())
    ) or "| _sin metadata adicional_ | — |"

    raw_record = {
        "report_id": report_id,
        "thread_id": report.get("thread_id"),
        "thread_slug": report.get("thread_slug"),
        "fingerprint": fp,
        "error_code": report.get("error_code"),
        "message": report.get("message"),
        "game_version": report.get("game_version"),
        "platform": report.get("platform"),
        "scene": report.get("scene"),
        "stack_trace": report.get("stack_trace"),
        "metadata": metadata,
        "created_at": report.get("created_at"),
        "published_at": report.get("published_at"),
    }

    return f"""<!-- AUTO-GENERATED by .github/workflows/bug-log-sync.yml. Do not store secrets here. -->
# Bug report `{report_id}`

> Registro técnico generado automáticamente a partir de un reporte ya sanitizado por el servidor de ByeTale.

## Correlación

| Campo | Valor |
| --- | --- |
| Report ID | `{esc(report_id)}` |
| Thread ID | `{esc(thread_id)}` |
| Hilo del foro | {forum_line} |
| Fingerprint | `{fp}` |
| Recibido | `{esc(report.get('created_at') or 'desconocido')}` |
| Publicado | `{esc(report.get('published_at') or 'desconocido')}` |

## Problema indicado por el jugador

{esc(report.get('message')) or '_sin descripción_'}

## Contexto del cliente

| Campo | Valor |
| --- | --- |
| Error code | `{esc(report.get('error_code'))}` |
| Versión | `{esc(report.get('game_version'))}` |
| Plataforma | `{esc(report.get('platform'))}` |
| Escena / mapa | `{esc(report.get('scene'))}` |

## Stack trace / contexto técnico

{code_block(stack)}

## Metadata de runtime

| Clave | Valor |
| --- | --- |
{metadata_rows}

## Registro sanitizado para análisis

```json
{json.dumps(raw_record, ensure_ascii=False, indent=2, sort_keys=True)}
```

## Privacidad

Este espejo no contiene `installation_id`, hashes de instalación, tokens, correo, IP, chat ni credenciales. El servidor elimina o evita esos datos antes de que el reporte llegue a este registro.
"""


def write_index(reports: list[dict[str, object]]) -> None:
    groups: dict[str, list[dict[str, object]]] = {}
    for report in reports:
        groups.setdefault(text(report["fingerprint"]), []).append(report)

    def sort_key(report: dict[str, object]) -> str:
        return text(report.get("created_at"))

    summary_rows: list[tuple[str, str, int, str, str, str, str]] = []
    for fp, items in groups.items():
        items.sort(key=sort_key)
        latest = items[-1]
        versions = sorted(
            {text(item.get("game_version")) for item in items if text(item.get("game_version"))}
        )
        summary_rows.append(
            (
                text(latest.get("created_at")),
                fp,
                len(items),
                text(latest.get("error_code")),
                text(latest.get("scene")),
                ", ".join(versions[-5:]),
                text(latest.get("report_id")),
            )
        )
    summary_rows.sort(reverse=True)

    now = dt.datetime.now(dt.timezone.utc).isoformat()
    lines = [
        "# ByeTale · Bug report index",
        "",
        f"_Sincronizado automáticamente: `{now}` · {len(reports)} reportes · {len(groups)} fingerprints._",
        "",
        "## Grupos de incidencias",
        "",
        "| Fingerprint | Ocurrencias | Error | Escena | Versiones recientes | Último reporte |",
        "| --- | ---: | --- | --- | --- | --- |",
    ]
    for _created, fp, count, code, scene, versions, report_id in summary_rows:
        lines.append(
            f"| `{fp}` | {count} | `{esc(code)}` | `{esc(scene)}` | "
            f"{esc(versions)} | [{report_id}]({report_id}.md) |"
        )

    lines.extend(["", "## Reportes recientes", ""])
    for report in sorted(reports, key=sort_key, reverse=True)[:100]:
        report_id = text(report.get("report_id"))
        lines.append(
            f"- [{report_id}]({report_id}.md) · `{esc(report.get('game_version'))}` · "
            f"`{esc(report.get('error_code'))}` · {esc(report.get('scene'))}"
        )

    (BASE / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    BASE.mkdir(parents=True, exist_ok=True)
    reports = fetch_reports()
    indexed: list[dict[str, object]] = []

    for report in reports:
        report_id = text(report.get("report_id")).strip()
        if not report_id:
            continue
        report["fingerprint"] = fingerprint(report)
        indexed.append(report)
        (BASE / f"{report_id}.md").write_text(render_report(report), encoding="utf-8")

    write_index(indexed)
    print(f"Exported {len(indexed)} published reports into {BASE}")


if __name__ == "__main__":
    main()
