"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {authErrorMessage} from "../../../lib/auth";
import {ensureForumProfile,slugifyForumTitle,uploadForumImage} from "../../../lib/forum-client";
import {neon} from "../../../lib/neon-client";
import "../forum.css"; import "./reportar.css";
const API="https://br-lively-unit-aygkh67q-bugreport.compute.c-5.us-east-2.aws.neon.tech/";
type Report={id:string;error_code:string;error_message:string;game_version:string;platform:string|null;scene:string|null;stack_trace:string|null;metadata:Record<string,string|number|boolean>;claimed_thread_id:string|null};
function bodyFor(r:Report|null,n:string){const x=["Nota del jugador:",n.trim()];if(r)x.push("","Datos técnicos:",`Código: ${r.error_code}`,`Mensaje: ${r.error_message}`,`Versión: ${r.game_version}`,`Plataforma: ${r.platform||"No indicada"}`,`Escena: ${r.scene||"No indicada"}`,...Object.entries(r.metadata||{}).map(([k,v])=>`${k}: ${v}`),...(r.stack_trace?["","Traza:",r.stack_trace]:[]));return x.join("\n")}
export default function Reportar(){const session=neon.auth.useSession(),user=session.data?.user??null;const[rid,setRid]=useState<string|null>(null),[token,setToken]=useState<string|null>(null),[report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false),[image,setImage]=useState<File|null>(null);
useEffect(()=>{const id=new URLSearchParams(location.search).get("report"),t=new URLSearchParams(location.hash.slice(1)).get("token");setRid(id);setToken(t);if(!id||!t){setLoading(false);return}fetch(`${API}?report=${encodeURIComponent(id)}`,{headers:{"x-report-token":t}}).then(async x=>{const p=await x.json();if(!x.ok)throw Error("Este informe ha caducado o no existe.");setReport(p);if(p.claimed_thread_id)setDone(true)}).catch(e=>setError(authErrorMessage(e))).finally(()=>setLoading(false))},[]);
const title=useMemo(()=>report?`${report.error_code}${report.scene?` en ${report.scene}`:""}`.slice(0,120):"Bug encontrado en ByeTale",[report]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user){const next=location.pathname+location.search+location.hash;location.href=`/account?mode=signin&next=${encodeURIComponent(next)}`;return}setBusy(true);setError("");try{const f=new FormData(e.currentTarget),t=String(f.get("title")||"").trim(),note=String(f.get("note")||"").trim();if(t.length<6||t.length>120)throw Error("El título debe tener entre 6 y 120 caracteres.");if(note.length<10||note.length>5000)throw Error("La nota debe tener entre 10 y 5.000 caracteres.");const body=bodyFor(report,note);if(body.length>10000)throw Error("El informe completo es demasiado largo.");const profile=await ensureForumProfile(user),imageUrl=await uploadForumImage(profile,image,session.data?.session?.token);const result=await neon.rpc("create_bug_thread",{p_title:t,p_slug:slugifyForumTitle(t),p_body:body,p_image_url:imageUrl,p_version:report?.game_version??null,p_platform:report?.platform??null,p_report_id:rid,p_report_token:token});if(result.error||!result.data)throw result.error??Error("No se pudo publicar.");history.replaceState(null,"","/forum/reportar");setDone(true)}catch(x){setError(authErrorMessage(x))}finally{setBusy(false)}}
return <main className="forumPage reportPage"><header className="forumHeader"><div className="forumShell forumNav"><Link className="forumBrand" href="/">BYETALE<small>Centro de incidencias</small></Link><nav className="forumNavLinks"><Link href="/forum">Foro</Link><Link href="/">Inicio</Link></nav></div></header><div className="reportShell"><section className="reportIntro"><span className="forumEyebrow">Reporte de bug</span><h1>Cuéntanos qué ocurrió</h1><p>Revisa los datos recogidos por el juego y añade el contexto que nos falta. Nada se publica hasta que tú lo confirmas.</p></section>{loading?<div className="reportCard loadingLine"><i className="loadingDot"/>Recuperando informe…</div>:done?<section className="reportCard success"><h2>Reporte enviado</h2><p>Ya está centralizado en el apartado Bugs.</p><Link className="forumButton primary" href="/forum">Ver los bugs</Link></section>:<div className="reportGrid"><form className="reportCard reportForm" onSubmit={submit}><h2>Lo que viste</h2>{error&&<div className="forumError">{error}</div>}<label><span>Título</span><input name="title" defaultValue={title} minLength={6} maxLength={120} required/></label><label><span>¿Dónde estabas y qué hacías?</span><textarea name="note" minLength={10} maxLength={5000} required placeholder="Acababa de entrar en la ciudad y abrí el inventario…"/></label><label className="fileField"><span>Captura opcional</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setImage(e.target.files?.[0]??null)}/><small>PNG, JPG o WEBP · máximo 3 MB</small></label><button className="forumButton primary" disabled={busy}>{busy?"Enviando…":user?"Enviar al apartado Bugs":"Iniciar sesión y continuar"}</button></form><aside className="reportCard technical"><h2>Datos del juego</h2>{report?<dl><div><dt>Código</dt><dd>{report.error_code}</dd></div><div><dt>Mensaje</dt><dd>{report.error_message}</dd></div><div><dt>Versión</dt><dd>{report.game_version}</dd></div><div><dt>Plataforma</dt><dd>{report.platform||"No indicada"}</dd></div><div><dt>Escena</dt><dd>{report.scene||"No indicada"}</dd></div></dl>:<p>Reporte manual, sin diagnóstico automático.</p>}{report?.stack_trace&&<details><summary>Ver traza</summary><pre>{report.stack_trace}</pre></details>}<p className="privacy">Rutas locales, correos y posibles tokens se eliminan antes de guardar.</p></aside></div>}</div></main>}
